// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDcvu5HqXF1_2hinGVw1nzwRJYC2yLFbA',
    appId: '1:472031386690:web:92920412af5e2f26a521db',
    messagingSenderId: '472031386690',
    projectId: 'flutter-task-4fb38',
    authDomain: 'flutter-task-4fb38.firebaseapp.com',
    storageBucket: 'flutter-task-4fb38.appspot.com',
    measurementId: 'G-2QJDKYV06S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVDCsbhgus6MZDoSqflrGQijcuY2XWn0o',
    appId: '1:472031386690:android:342ba84c894d53aba521db',
    messagingSenderId: '472031386690',
    projectId: 'flutter-task-4fb38',
    storageBucket: 'flutter-task-4fb38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGe4q5psYQTzlByxg7HBwHldIG4lyFbWc',
    appId: '1:472031386690:ios:354cef16143b201fa521db',
    messagingSenderId: '472031386690',
    projectId: 'flutter-task-4fb38',
    storageBucket: 'flutter-task-4fb38.appspot.com',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGe4q5psYQTzlByxg7HBwHldIG4lyFbWc',
    appId: '1:472031386690:ios:354cef16143b201fa521db',
    messagingSenderId: '472031386690',
    projectId: 'flutter-task-4fb38',
    storageBucket: 'flutter-task-4fb38.appspot.com',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDcvu5HqXF1_2hinGVw1nzwRJYC2yLFbA',
    appId: '1:472031386690:web:750cdb71ed2670f1a521db',
    messagingSenderId: '472031386690',
    projectId: 'flutter-task-4fb38',
    authDomain: 'flutter-task-4fb38.firebaseapp.com',
    storageBucket: 'flutter-task-4fb38.appspot.com',
    measurementId: 'G-8HV28J6P9W',
  );
}
